stages:
  - solve_sudoku

variables:
  GIT_STRATEGY: clone

solve_sudoku_9_example:
  image: ubuntu:24.04

  stage: solve_sudoku

  script:
    - |

      apt-get update && apt-get install -y \
      build-essential \
      gcc \
      g++ \
      make \
      cmake \
      pkg-config \
      git \
      && apt-get clean \
      && rm -rf /var/lib/apt/lists/*

      echo "Solving a sudoku 9 by 9 example..."

      make -j$(nproc)

      cd bin/ 
      
      ./sudoku.out

      make clean
